--------------------------------------------------------
--  File created - Sunday-May-08-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AIRPORT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."AIRPORT" 
   (	"AIRPORTID" VARCHAR2(5 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"ZIPCODE" VARCHAR2(5 BYTE), 
	"STATE" CHAR(2 BYTE), 
	"WEBSITE" VARCHAR2(50 BYTE), 
	"AIRPORTNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONNECTION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CONNECTION" 
   (	"AIRPORTID" VARCHAR2(5 BYTE), 
	"FLIGHTID" VARCHAR2(5 BYTE), 
	"ARIVALDATE" DATE, 
	"STOPOVER" VARCHAR2(20 BYTE), 
	"DEPARTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CUSTOMER" 
   (	"CUSTOMERID" VARCHAR2(10 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"ZIPCODE" VARCHAR2(5 BYTE), 
	"STATE" CHAR(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLIGHT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."FLIGHT" 
   (	"FLIGHTID" VARCHAR2(5 BYTE), 
	"DEPARTCITY" VARCHAR2(20 BYTE), 
	"DEPARTDATE" DATE, 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"ARIVALDATE" DATE, 
	"FLIGHTCOST" NUMBER(5,2), 
	"FLIGHTTYPE" VARCHAR2(20 BYTE), 
	"STOPS_AT" VARCHAR2(2 BYTE), 
	"STOP_DURATION" VARCHAR2(20 BYTE), 
	"FLIGHTINDEX" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESERVATION" 
   (	"RESERVATIONCODE" VARCHAR2(100 BYTE), 
	"FLIGHTID" VARCHAR2(5 BYTE), 
	"CUSTOMERID" VARCHAR2(10 BYTE), 
	"CREDITCARD" VARCHAR2(16 BYTE), 
	"EXPMONTH" NUMBER(*,0), 
	"EXPYEAR" NUMBER(*,0), 
	"AMOUNT" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMIN.AIRPORT
SET DEFINE OFF;
Insert into ADMIN.AIRPORT (AIRPORTID,EMAIL,PHONE,ADDRESS,CITY,ZIPCODE,STATE,WEBSITE,AIRPORTNAME) values ('A01','A01@company.com','7180000000','111 Jay St','Brooklyn','10021','NY','www.arport.com','Airport One');
REM INSERTING into ADMIN.CONNECTION
SET DEFINE OFF;
REM INSERTING into ADMIN.CUSTOMER
SET DEFINE OFF;
Insert into ADMIN.CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,DOB,EMAIL,PHONE,ADDRESS,CITY,ZIPCODE,STATE) values ('C01',null,null,null,null,null,null,null,null,null);
Insert into ADMIN.CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,DOB,EMAIL,PHONE,ADDRESS,CITY,ZIPCODE,STATE) values ('993995','fatima','fatima',to_date('09-SEP-00','DD-MON-RR'),'hggh','347','ddd','kjhkj','87','AL');
Insert into ADMIN.CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,DOB,EMAIL,PHONE,ADDRESS,CITY,ZIPCODE,STATE) values ('1234','John','Doe',to_date('09-JAN-90','DD-MON-RR'),'JDoe@mail.com','7181112222','111 abc St','New York','10001','NY');
Insert into ADMIN.CUSTOMER (CUSTOMERID,FIRSTNAME,LASTNAME,DOB,EMAIL,PHONE,ADDRESS,CITY,ZIPCODE,STATE) values ('12345','John','Doe',to_date('09-SEP-90','DD-MON-RR'),'JDoe@mail.com','7181112222','111 abc St','New York','10001','NY');
REM INSERTING into ADMIN.FLIGHT
SET DEFINE OFF;
Insert into ADMIN.FLIGHT (FLIGHTID,DEPARTCITY,DEPARTDATE,DESTINATION,ARIVALDATE,FLIGHTCOST,FLIGHTTYPE,STOPS_AT,STOP_DURATION,FLIGHTINDEX) values ('F013','CA',to_date('09-SEP-16','DD-MON-RR'),'NY',to_date('09-OCT-16','DD-MON-RR'),900,'Direct',null,null,3);
Insert into ADMIN.FLIGHT (FLIGHTID,DEPARTCITY,DEPARTDATE,DESTINATION,ARIVALDATE,FLIGHTCOST,FLIGHTTYPE,STOPS_AT,STOP_DURATION,FLIGHTINDEX) values ('F001','CA',to_date('09-SEP-16','DD-MON-RR'),'DC',to_date('09-OCT-16','DD-MON-RR'),900,'Direct',null,null,21);
Insert into ADMIN.FLIGHT (FLIGHTID,DEPARTCITY,DEPARTDATE,DESTINATION,ARIVALDATE,FLIGHTCOST,FLIGHTTYPE,STOPS_AT,STOP_DURATION,FLIGHTINDEX) values ('F001','CA',to_date('09-SEP-16','DD-MON-RR'),'DC',to_date('09-OCT-16','DD-MON-RR'),900,'Direct','GA','2hrs',22);
REM INSERTING into ADMIN.RESERVATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AIRPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."AIRPORT_PK" ON "ADMIN"."AIRPORT" ("AIRPORTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TABLE1_PK" ON "ADMIN"."CONNECTION" ("AIRPORTID", "FLIGHTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."CUSTOMER_PK" ON "ADMIN"."CUSTOMER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FLIGHT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."FLIGHT_PK" ON "ADMIN"."FLIGHT" ("FLIGHTINDEX", "FLIGHTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."RESERVATION_PK" ON "ADMIN"."RESERVATION" ("RESERVATIONCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESERVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."RESERVE_PK" ON "ADMIN"."RESERVATION" ("FLIGHTID", "CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AIRPORT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."AIRPORT" ADD CONSTRAINT "AIRPORT_PK" PRIMARY KEY ("AIRPORTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."AIRPORT" MODIFY ("AIRPORTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONNECTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CONNECTION" MODIFY ("AIRPORTID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CONNECTION" MODIFY ("FLIGHTID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CONNECTION" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("AIRPORTID", "FLIGHTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."CUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FLIGHT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."FLIGHT" ADD CONSTRAINT "FLIGHT_PK" PRIMARY KEY ("FLIGHTINDEX", "FLIGHTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESERVATION" ADD CONSTRAINT "RESERVE_PK" PRIMARY KEY ("FLIGHTID", "CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("FLIGHTID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESERVATIONCODE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONNECTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CONNECTION" ADD CONSTRAINT "FLIGHT_AIRPORT_FK1" FOREIGN KEY ("AIRPORTID")
	  REFERENCES "ADMIN"."AIRPORT" ("AIRPORTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESERVATION" ADD CONSTRAINT "RESERVATION_CUSTOMER_FK1" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "ADMIN"."CUSTOMER" ("CUSTOMERID") ENABLE;
